fail_fast: false
default_language_version:
  python: python3
default_stages:
- commit
- push
minimum_pre_commit_version: 3.5.0
repos:
- repo: https://github.com/google/yapf
  rev: v0.40.0
  hooks:
    - id: yapf
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
